<?php
/**
 * Auto generated by prado-cli.php on 2008-12-25 05:48:22.
 */
class ActivityInoutputView extends TActiveRecord
{
	const TABLE='vv_activity_inoutput';

	public $idtm_inoutput_has_tm_activity;
	public $idtm_activity;
	public $idtm_inoutput;
	public $ino_link_type;
	public $act_name;
	public $ino_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>