<?php
/**
 * Auto generated by prado-cli.php on 2009-04-10 08:49:30.
 */
class PivotStammdatenGroupView extends TActiveRecord
{
	const TABLE='vv_pivot_stammdaten_group';

	public $idtm_pivot;
	public $idta_pivot_bericht;
	public $idta_stammdaten_group;
	public $parent_idtm_pivot;
	public $pivot_position;
	public $pivot_filter;
	public $stammdaten_group_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>