<?php
/**
 * Auto generated by prado-cli.php on 2010-08-16 11:05:47.
 */
class ProtokollDetailView extends TActiveRecord
{
	const TABLE='vv_protokoll_detail';

	public $idtm_protokoll_detail;
	public $idtm_activity;
	public $idtm_protokoll_detail_group;
	public $prtdet_topic;
	public $prtdet_descr;
	public $prtdet_cdate;
	public $idtm_user;
	public $idta_protokoll_ergebnistype;
	public $prtdet_wvl;
	public $prtdet_wvl_type;
	public $idtm_protokoll;
	public $act_name;
	public $act_pspcode;
	public $act_lft;
	public $act_rgt;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>