<?php
/**
 * Auto generated by prado-cli.php on 2010-10-27 10:32:29.
 */
class StammdatenGroupView extends TActiveRecord
{
	const TABLE='vv_stammdaten_group';

	public $stammdaten_group_original;
	public $stammdaten_group_create;
	public $stammdaten_group_multi;
	public $stammdaten_group_name;
	public $idta_struktur_type;
	public $idtt_stammdatensicht;
	public $idta_stammdaten_group;
	public $parent_idta_stammdaten_group;
	public $idta_stammdatensicht;
        public $sts_stammdaten_group_use;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>