<?php
/**
 * Auto generated by prado-cli.php on 2010-01-04 01:22:46.
 */
class TerminRessourceOrganisationView extends TActiveRecord
{
	const TABLE='vv_termin_ressource_organisation';

	public $idtm_termin;
	public $ter_startdate;
	public $ter_enddate;
	public $ter_starttime;
	public $ter_endtime;
	public $idtm_organisation;
	public $idtm_ressource;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>