<?php
/**
 * Auto generated by prado-cli.php on 2008-12-26 08:42:41.
 */
class TerminOrganisationView extends TActiveRecord
{
	const TABLE='vv_termin_organisation';

	public $idtm_termin;
	public $idtm_organisation;
	public $idtm_termin_organisation;
	public $org_name;
	public $user_role_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>