<?php
/**
 * Auto generated by prado-cli.php on 2009-01-08 12:00:26.
 */
class VerteilerOrganisationView extends TActiveRecord
{
	const TABLE='vv_verteiler_organisation';

	public $idtm_verteiler;
	public $idtm_organisation;
	public $idtm_verteiler_organisation;
	public $org_name;
	public $user_role_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>