<?php
/**
 * Auto generated by prado-cli.php on 2008-12-23 06:12:23.
 */
class ActivityActivityRecord extends TActiveRecord
{
	const TABLE='ta_activity_activity';

	public $idta_activity_activity;
	public $idtm_activity;
	public $pre_idtm_activity;
	public $actact_type;
        public $actact_minz;
	public $actact_maxz;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>