<?php
/**
 * Auto generated by prado-cli.php on 2008-12-20 10:56:49.
 */
class ActivityZieleRecord extends TActiveRecord
{
	const TABLE='tm_activity_has_tt_ziele';

	public $idtt_ziele;
	public $idtm_activity;
	public $idtm_activity_has_tt_ziele;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>