<?php
/**
 * Auto generated by prado-cli.php on 2009-08-05 04:24:42.
 */
class AutoMappingRecord extends TActiveRecord
{
	const TABLE='ta_automapping';

	public $idta_automapping;
	public $ima_name;
	public $idtm_stammdaten;
	public $idta_feldfunktion;
	public $ama_faktor;
	public $ama_lauf;
	public $ama_source;
	public $ama_id;
        public $ti_id;
        public $ti_label;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>