<?php
/**
 * Auto generated by prado-cli.php on 2009-07-14 04:43:09.
 */
class BerichtTypeRecord extends TActiveRecord
{
	const TABLE='ta_bericht_type';

	public $ber_type_name;
	public $ber_type_descr;
	public $idta_bericht_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>