<?php
/**
 * Auto generated by prado-cli.php on 2009-07-14 04:42:38.
 */
class BerichtStrukturRecord extends TActiveRecord
{
	const TABLE='ta_bericht_struktur';

	public $idta_bericht_struktur;
	public $idta_berichte;
	public $ber_struktur_name;
	public $ber_struktur_descr;
	public $parent_idta_bericht_struktur;
	public $idta_bericht_struktur_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>