<?php
/**
 * Auto generated by prado-cli.php on 2009-07-14 04:43:09.
 */
class BrancheRecord extends TActiveRecord
{
	const TABLE='ta_branche';

	public $bra_name;
	public $bra_code;
	public $idta_branche;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>