<?php
/**
 * Auto generated by prado-cli.php on 2008-04-25 01:34:42.
 */
class CountryRecord extends TActiveRecord
{
	const TABLE='tm_country';

	public $idtm_country;
	public $country_iso;
	public $country_ful;
	
	
	public static $RELATIONS=array
    (
        'adresse' => array(self::HAS_MANY, 'AdresseRecord','idta_adresse'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	
	
}
?>