<?php
/**
 * Auto generated by prado-cli.php on 2008-06-17 10:50:28.
 */
class FrachtRecord extends TActiveRecord
{
	const TABLE='ta_fracht';

	public $idta_fracht;
	public $fracht_auftragsnummer;
	public $fracht_status;
	public $fracht_sonstiges;
	public $idtm_fahrzeug_kategorie;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>