<?php
/**
 * Auto generated by prado-cli.php on 2008-06-17 10:50:58.
 */
class FrachtTeilladungRecord extends TActiveRecord
{
	const TABLE='ta_fracht_teilladung';

	public $idta_fracht_teilladung;
	public $idta_fracht;
	public $idta_adresse_auf;
	public $idtta_adresse_ab;
	public $fracht_teilladung_auf_dat_ab;
	public $fracht_teilladung_auf_dat_bis;
	public $fracht_teilladung_ab_dat_ab;
	public $fracht_teilladung_ab_dat_bis;
	public $fracht_teilladung_name;
	public $fracht_teilladung_temperatur;
	public $idta_waren;
	public $fracht_teilladung_beladung;
	public $fracht_teilladung_entladung;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>