<?php
/**
 * Auto generated by prado-cli.php on 2009-08-05 04:24:14.
 */
class ImportMappingRecord extends TActiveRecord
{
	const TABLE='tm_importmapping';

	public $idtm_importmapping;
	public $ima_name;
	public $ima_id1;
	public $ima_id2;
	public $ima_id3;
	public $ima_id4;
	public $ima_id5;
	public $ima_id6;
	public $ima_id7;
	public $ima_id8;
	public $ima_id9;
	public $ima_id10;
	public $idtm_struktur;
	public $idta_feldfunktion;
	public $ima_faktor;
	public $ima_lauf;
	public $ima_source;
	public $ima_path;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>