<?php
/**
 * Auto generated by prado-cli.php on 2010-01-05 10:10:32.
 */
class OrganisationAdresseRecord extends TActiveRecord
{
	const TABLE='tm_organisation_has_ta_adresse';

	public $idtm_organisation_has_ta_adresse;
	public $idtm_organisation;
	public $idta_adresse;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>