<?php
/**
 * Auto generated by prado-cli.php on 2008-09-15 10:06:52.
 */
class OrganisationTypeRecord extends TActiveRecord
{
	const TABLE='ta_organisation_type';

	public $idta_organisation_type;
	public $org_type_name;
        public $org_type_monat_jahr;

	public static $RELATIONS=array
    (
        'typeorg' => array(self::HAS_MANY, 'OrganisationRecord'),
    );
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>