<?php
/**
 * Auto generated by prado-cli.php on 2009-04-07 07:20:58.
 */
class PivotBerichtRecord extends TActiveRecord
{
	const TABLE='ta_pivot_bericht';

	public $idta_pivot_bericht;
	public $idtm_user;
	public $pivot_bericht_cdate;
	public $pivot_bericht_name;
	public $idta_feldfunktion;
	public $pivot_bericht_operator;
	public $idta_variante;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>