<?php
/**
 * Auto generated by prado-cli.php on 2009-01-05 10:51:54.
 */
class ProtokollErgebnistypeRecord extends TActiveRecord
{
	const TABLE='ta_protokoll_ergebnistype';

	public $idta_protokoll_ergebnistype;
	public $prt_ergtype_name;
	
	public static $RELATIONS=array
    (
      	'ergebnistypeprotokoll' => array(self::HAS_MANY, 'ProtokollDetailRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>