<?php
/**
 * Auto generated by prado-cli.php on 2008-09-19 07:35:37.
 */
class ProzessStepRecord extends TActiveRecord
{
	const TABLE='tm_prozess_step';

	public $idtm_prozess_step;
	public $prostep_name;
	public $prostep_descr;
	public $idtm_prozess;
	public $idtm_struktur;
	public $parent_idtm_prozess_step;
	public $idtm_organisation;
	public $error_idtm_prozess_step;
	public $prostep_valid;
	public $prostep_cdate;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>