<?php
/**
 * Auto generated by prado-cli.php on 2008-09-28 07:53:56.
 */
class RCValueRecord extends TActiveRecord
{
	const TABLE='tm_rcvalue';

	public $idtm_rcvalue;
	public $rcv_tabelle;
	public $rcv_id;
	public $idtm_organisation;
	public $rcv_type;
	public $rcv_comment;
	public $idtm_risiko;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static $RELATIONS=array
    (
        'rcvalueorganisation' => array(self::BELONGS_TO, 'OrganisationRecord'),
    	'rcvaluerisiko' => array(self::BELONGS_TO, 'RisikoRecord'),
    	'rcvaluercttvalue' => array(self::HAS_MANY, 'RCTTValueRecord'),
    );
}
?>