<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:17:01.
 */
class RessourceRecord extends TActiveRecord
{
	const TABLE='tm_ressource';

	public $idtm_ressource;
	public $res_name;
	public $res_code;
	public $idta_rescalendar;
	public $idta_ressource_type;
	public $res_produktivitaet;
	public $res_kosten;
	public $res_note;
	public $idta_einheit;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>