<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:15:12.
 */
class RessourceTypeRecord extends TActiveRecord
{
	const TABLE='ta_ressource_type';

	public $idta_ressource_type;
	public $res_type_name;
	public $res_type_descr;
	public $res_type_kosten;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>