<?php
/**
 * Auto generated by prado-cli.php on 2008-09-15 10:05:07.
 */
class RisikoRecord extends TActiveRecord
{
	const TABLE='tm_risiko';

	public $idtm_risiko;
	public $ris_name;
	public $ris_descr;
	public $parent_idtm_risiko;
	public $idta_risiko_type;
	
	public static $RELATIONS=array
    (
        'ristype' => array(self::BELONGS_TO, 'RisikoTypeRecord'),
    	'risikorcvalue' => array(self::HAS_MANY, 'RCValueRecord'),
    );
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>