<?php
/**
 * Auto generated by prado-cli.php on 2009-03-28 02:44:43.
 */
class StammdatenGroupRecord extends TActiveRecord
{
	const TABLE='ta_stammdaten_group';

	public $idta_stammdaten_group;
	public $stammdaten_group_name;
	public $idta_struktur_type;
        public $parent_idta_stammdaten_group;
	public $stammdaten_group_original;
	public $stammdaten_group_create;
        public $stammdaten_group_multi;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>