<?php
/**
 * Auto generated by prado-cli.php on 2010-10-27 04:33:42.
 */
class StammdatensichtRecord extends TActiveRecord
{
	const TABLE='ta_stammdatensicht';

	public $idta_stammdatensicht;
	public $sts_name;
	public $sts_aktiv;
	public $sts_reporting;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>