<?php
/**
 * Auto generated by prado-cli.php on 2009-03-28 02:45:17.
 */
class StammdatenRecord extends TActiveRecord
{
	const TABLE='tm_stammdaten';

	public $idtm_stammdaten;
	public $stammdaten_name;
	public $stammdaten_key_extern;
	public $idta_stammdaten_group;
        public $stammdaten_aktiv;

        //hier kommen meine virtuellen member

        public $ttstammdaten_created;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>