<?php
/**
 * Auto generated by prado-cli.php on 2009-04-15 11:11:54.
 */
class StrukturStrukturRecord extends TActiveRecord
{
	const TABLE='tm_struktur_tm_struktur';

	public $idtm_struktur_tm_struktur;
	public $idtm_struktur_from;
	public $idtm_struktur_to;
	public $idta_feldfunktion;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>