<?php
/**
 * Auto generated by prado-cli.php on 2009-04-23 10:24:05.
 */
class StrukturBerichtZeilenRecord extends TActiveRecord
{
	const TABLE='ta_struktur_bericht_zeilen';

	public $idta_struktur_bericht_zeilen;
	public $idta_feldfunktion;
	public $sbz_spacer_label;
	public $sbz_type;
	public $sbz_detail;
	public $sbz_label;
	public $idta_struktur_bericht;
	public $sbz_order;
	public $sbz_input;
	public $idtm_stammdaten;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>