<?php
/**
 * Auto generated by prado-cli.php on 2009-08-04 08:02:08.
 */
class TempImportRecord extends TActiveRecord
{
	const TABLE='tm_tempimport';

	public $idtm_tempimport;
	public $ti_name;
	public $user_name;
	public $ti_id1;
	public $ti_id2;
	public $ti_id3;
	public $ti_id4;
	public $ti_id5;
	public $ti_id6;
	public $ti_id7;
	public $ti_id8;
	public $ti_id9;
	public $ti_id10;
	public $ti_label1;
	public $ti_label2;
	public $ti_label3;
	public $ti_label4;
	public $ti_label5;
	public $ti_label6;
	public $ti_label7;
	public $ti_label8;
	public $ti_label9;
	public $ti_label10;
	public $ti_value1;
	public $ti_value2;
	public $ti_value3;
	public $ti_value4;
	public $per_intern;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>