<?php
/**
 * Auto generated by prado-cli.php on 2008-12-26 02:02:00.
 */
class TerminRecord extends TActiveRecord
{
	const TABLE='tm_termin';

	public $idtm_termin;
	public $ter_betreff;
	public $ter_descr;
	public $ter_ort;
	public $ter_startdate;
	public $ter_starttime;
	public $ter_enddate;
	public $ter_endtime;
	public $idtm_activity;
        public $idta_termin_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>