<?php
/**
 * Auto generated by prado-cli.php on 2009-03-12 09:21:37.
 */
class TTMessageRecord extends TActiveRecord
{
	const TABLE='tt_message';

	public $idtt_message;
	public $mes_date;
	public $to_idtm_organisation;
	public $from_idtm_organisation;
	public $mes_content;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>