<?php
/**
 * Auto generated by prado-cli.php on 2009-11-18 06:29:27.
 */
class TTUserLogRecord extends TActiveRecord
{
	const TABLE='tt_user_log';

	public $idtt_user_log;
	public $idtm_user;
	public $ul_status;
	public $ul_ipadress;
	public $ul_time;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>