<?php
/**
 * Auto generated by prado-cli.php on 2008-11-30 07:22:00.
 */
class TTZieleRecord extends TActiveRecord
{
	const TABLE='tt_ziele';

	public $idtt_ziele;
	public $ttzie_name;
	public $ttzie_descr;
	public $idtm_prozess;
	public $idtm_ziele;
	public $idtm_organisation;
	public $error_idtt_ziele;
	public $prostep_valid;
	public $prostep_cdate;
	
	public static $RELATIONS=array
    (
        'ttzieleact' => array(self::HAS_MANY, 'ActivityRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>