<?php
/**
 * Auto generated by prado-cli.php on 2009-01-05 10:50:52.
 */
class VerteilerOrganisationRecord extends TActiveRecord
{
	const TABLE='tm_verteiler_organisation';

	public $idtm_verteiler;
	public $idtm_organisation;
	public $idtm_verteiler_organisation;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>