<?php
/**
 * Auto generated by prado-cli.php on 2009-07-20 08:38:12.
 */
class WorkflowRecord extends TActiveRecord
{
	const TABLE='tt_workflow';

	public $idtt_workflow;
	public $wfl_modul;
	public $wfl_id;
	public $idtm_user;
	public $idta_periode;
	public $idta_variante;
	public $wfl_cdate;
	public $wfl_status;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>