<?php
/**
 * Auto generated by prado-cli.php on 2008-11-30 07:21:03.
 */
class ZieleRecord extends TActiveRecord
{
	const TABLE='tm_ziele';

	public $idtm_ziele;
	public $zie_name;
	public $zie_descr;
	public $parent_idtm_ziele;
	public $idta_ziele_type;
        //public $idtm_activity; herausgenommen... pf 20090702
	
	public static $RELATIONS=array
    (
        'zieletype' => array(self::BELONGS_TO, 'ZieleTypeRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>