<?php
/**
 * Auto generated by prado-cli.php on 2008-12-20 10:58:06.
 */
class ActivityRecord extends TActiveRecord
{
	const TABLE='tm_activity';

	public $idtm_activity;
	public $act_name;
	public $act_descr;
	public $act_startdate;
	public $act_enddate;
	public $act_dauer;
	public $act_fortschritt;
	public $idta_activity_type;
	public $idtm_organisation;
	public $parent_idtm_activity;
	public $act_step;
	public $act_pspcode;
	public $act_faz;
	public $act_fez;
	public $act_saz;
	public $act_sez;
	public $act_gp;
	public $act_fp;
        public $act_kosten;
        public $act_colorcode;
        public $act_lft;
        public $act_rgt;
	
	//folgende Felder gibt es in der DB nicht!!!
	public $ttact_hasPrevious;
	public $ttact_gp;
	public $ttact_fp;
	public $ttact_faz;
	public $ttact_fez;
	public $ttact_saz;
	public $ttact_sez;
        public $ttact_startdate;
	public $ttact_enddate;
        //fuer die Kosten
        public $ttact_kosten;
        public $ttact_iscalculated;


	public static $RELATIONS=array
    (
        'acttype' => array(self::BELONGS_TO, 'ActivityTypeRecord'),
    	'actorganisation' => array(self::BELONGS_TO, 'OrganisationRecord'),
    	'actttziele' => array(self::BELONGS_TO, 'TTZieleRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>