<?php
/**
 * Auto generated by prado-cli.php on 2008-12-08 02:33:51.
 */
class ActivityParticipantsRecord extends TActiveRecord
{
	const TABLE='tm_activity_participants';

	public $idtm_activity;
	public $idtm_organisation;
	public $idtm_activity_participant;
	public $act_part_anwesend;
	public $act_part_notiz;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>