<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 12:00:39.
 */
class AdresseRecord extends TActiveRecord
{
	const TABLE='ta_adresse';

	public $idta_adresse;
	public $adresse_street;
	public $adresse_zip;
	public $adresse_town;
	public $idtm_country;
	public $adresse_lat;
	public $adresse_long;
        public $adresse_ismain;
	
	public static $RELATIONS=array
    (
        'adressewaren' => array(self::HAS_MANY, 'WarenRecord'),
    	'adresseparteien' => array(self::HAS_MANY, 'ParteiAdresseRecord','fk_idta_adresse'),
    	'country' => array(self::BELONGS_TO, 'CountryRecord','fk_idtm_country'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>