<?php
/**
 * Auto generated by prado-cli.php on 2009-04-05 12:56:20.
 */
class AufgabeRessourceRecord extends TActiveRecord
{
	const TABLE='tm_aufgabe_ressource';

	public $idtm_aufgabe_ressource;
	public $idtm_aufgabe;
	public $idtm_ressource;
	public $auf_res_dauer;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>