<?php
/**
 * Auto generated by prado-cli.php on 2010-01-09 01:01:13.
 */
class AufgabenTypeRecord extends TActiveRecord
{
	const TABLE='ta_aufgaben_type';

	public $idta_aufgaben_type;
	public $auf_type_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>