<?php
/**
 * Auto generated by prado-cli.php on 2010-01-05 08:37:17.
 */
class BankkontoRecord extends TActiveRecord
{
	const TABLE='ta_bankkonto';

	public $idta_bankkonto;
	public $bak_kontowortlaut;
	public $bak_geldinstitut;
	public $bak_blz;
	public $bak_konto;
	public $bak_bic;
	public $bak_iban;
	public $idtm_organisation;
	public $bak_ismain;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>