<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:21:27.
 */
class BerechtigungRecord extends TActiveRecord
{
	const TABLE='xx_berechtigung';

	public $idxx_berechtigung;
	public $xx_modul;
	public $xx_id;
	public $xx_read;
	public $xx_write;
	public $xx_create;
	public $xx_delete;
	public $idtm_user;
	public $xx_parameter1;
	public $xx_parameter2;
	public $xx_parameter3;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>