<?php
/**
 * Auto generated by prado-cli.php on 2009-07-16 09:49:48.
 */
class BerichteOrganisationRecord extends TActiveRecord
{
	const TABLE='tm_berichte_has_organisation';

	public $idtm_berichte_has_organisation;
	public $idta_berichte;
	public $idtm_organisation;
	public $bho_modul;
	public $bho_id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>