<?php
/**
 * Auto generated by prado-cli.php on 2009-07-14 04:43:43.
 */
class BerichtStrukturTypeRecord extends TActiveRecord
{
	const TABLE='ta_bericht_struktur_type';

	public $ber_struktur_type_name;
	public $ber_struktur_type_descr;
	public $idta_bericht_struktur_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>