<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:00:27.
 */
class ContentContainerTypeRecord extends TActiveRecord
{
	const TABLE='ta_contentcontainer_type';

	public $cc_type_name;
	public $cc_type_descr;
	public $idta_contentcontainer_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>