<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 04:59:52.
 */
class ContentContainerRecord extends TActiveRecord
{
	const TABLE='ta_contentcontainer';

	public $idta_contentcontainer;
	public $idta_bericht_struktur;
	public $idta_contentcontainer_type;
	public $ccc_name;
	public $ccc_cdate;
	public $idtm_organisation;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>