<?php
/**
 * Auto generated by prado-cli.php on 2010-10-29 03:49:46.
 */
class CustomMaskFieldRecord extends TActiveRecord
{
	const TABLE='ta_custommask_fields';

	public $idta_custommask_fields;
	public $cuf_maskenname;
	public $cuf_maskenid;
	public $idta_perioden;
	public $idta_variante;
	public $idta_feldfunktion;
	public $idtm_stammdaten;
	public $cuf_numberformat;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>