<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:08:01.
 */
class EinheitRecord extends TActiveRecord
{
	const TABLE='ta_einheit';

	public $idta_einheit;
	public $ein_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>