<?php
/**
 * Auto generated by prado-cli.php on 2008-06-17 10:50:02.
 */
class FahrzeugKategorieRecord extends TActiveRecord
{
	const TABLE='tm_fahrzeug_kategorie';

	public $idtm_fahrzeug_kategorie;
	public $fahrzeug_kategorie_name;
	public $fahrzeug_kategorie_beschreibung;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>