<?php
/**
 * Auto generated by prado-cli.php on 2009-07-30 08:46:27.
 */
class FahrtenbuchRecord extends TActiveRecord
{
	const TABLE='tm_fahrtenbuch';

	public $idtm_fahrtenbuch;
	public $idtm_zeiterfassung;
	public $fahrt_von;
	public $fahrt_nach;
	public $fahrt_status;
	public $fahrt_km;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>