<?php
/**
 * Auto generated by prado-cli.php on 2008-10-04 01:39:58.
 */
class FeldfunktionRecord extends TActiveRecord
{
	const TABLE='ta_feldfunktion';

	public $idta_feldfunktion;
	public $ff_name;
	public $pre_idta_feldfunktion;
	public $ff_operator;
	public $ff_descr;
	public $idta_struktur_type;
	public $ff_faktor;
	public $ff_fix;
	public $ff_gewichtung;
	public $ff_type; //hier steht 0 summe und 1 durchschnitt
	public $ff_default; //mein startwert
    public $ff_readonly;
    public $ff_order;
    public $ff_calcopening;
    public $ff_cashbalance;
	
	public static $RELATIONS=array
    (
        'feldfunktioncollector' => array(self::HAS_MANY, 'CollectorRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>