<?php
/**
 * Auto generated by prado-cli.php on 2009-10-27 08:34:52.
 */
class FortschreibungRecord extends TActiveRecord
{
	const TABLE='ta_fortschreibung';

	public $idta_fortschreibung;
	public $for_name;
	public $idtm_struktur;
	public $from_idta_periode;
	public $to_idta_periode;
	public $idta_variante;
	public $for_faktor;
	public $idta_feldfunktion;
        public $idta_fortschreibungs_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>