<?php
/**
 * Auto generated by prado-cli.php on 2008-12-20 11:01:36.
 */
class InoutputTypeRecord extends TActiveRecord
{
	const TABLE='ta_inoutput_type';

	public $idta_inoutput_type;
	public $ino_type_name;
	public $ino_type_descr;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>