<?php
/**
 * Auto generated by prado-cli.php on 2008-12-20 11:01:03.
 */
class InoutputRecord extends TActiveRecord
{
	const TABLE='tm_inoutput';

	public $idtm_inoutput;
	public $ino_tabelle;
	public $ino_id;
	public $idta_inoutput_type;
	public $ino_descr;
	public $ino_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>