<?php
/**
 * Auto generated by prado-cli.php on 2008-12-24 07:48:43.
 */
class InoutputActivityRecord extends TActiveRecord
{
	const TABLE='tm_inoutput_has_tm_activity';

	public $idtm_inoutput_has_tm_activity;
	public $idtm_activity;
	public $idtm_inoutput;
	public $ino_link_type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>