<?php
/**
 * Auto generated by prado-cli.php on 2010-01-08 04:12:06.
 */
class KommunikationRecord extends TActiveRecord
{
	const TABLE='ta_kommunikation';

	public $idta_kommunikation;
	public $kom_type;
	public $kom_information;
	public $kom_ismain;
	public $idtm_organisation;
        public $kom_ismainmain;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>