<?php
/**
 * Auto generated by prado-cli.php on 2009-03-15 08:20:58.
 */
class KostenStatusRecord extends TActiveRecord
{
	const TABLE='ta_kosten_status';

	public $idta_kosten_status;
	public $kst_status_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>