<?php
/**
 * Auto generated by prado-cli.php on 2008-04-29 09:42:54.
 */
class ParteiAdresseRecord extends TActiveRecord
{
	const TABLE='ta_partei_has_ta_adresse';

	public $idta_partei;
	public $idta_adresse;
	
	public static $RELATIONS=array
    (
        'parteien' => array(self::BELONGS_TO, 'ParteiRecord','idta_partei'),
    	'adressen' => array(self::BELONGS_TO, 'AdresseRecord','idta_adresse'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>