<?php
/**
 * Auto generated by prado-cli.php on 2008-10-06 07:03:53.
 */
class PeriodenRecord extends TActiveRecord
{
	const TABLE='ta_perioden';

	public $idta_perioden;
	public $per_intern;
	public $per_extern;
	public $parent_idta_perioden;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>