<?php
/**
 * Auto generated by prado-cli.php on 2009-04-07 07:21:18.
 */
class PivotRecord extends TActiveRecord
{
	const TABLE='tm_pivot';

	public $idtm_pivot;
	public $idta_pivot_bericht;
	public $idta_stammdaten_group;
	public $parent_idtm_pivot;
	public $pivot_position;
	public $pivot_filter;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>