<?php
/**
 * Auto generated by prado-cli.php on 2009-01-05 10:52:29.
 */
class ProtokollTypeRecord extends TActiveRecord
{
	const TABLE='ta_protokoll_type';

	public $idta_protokoll_type;
	public $prt_type_name;
	
	public static $RELATIONS=array
    (
      	'typeprotokoll' => array(self::HAS_MANY, 'ProtokollRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>