<?php
/**
 * Auto generated by prado-cli.php on 2008-12-10 10:46:43.
 */
class ProtokollDetailRecord extends TActiveRecord
{
	const TABLE='tm_protokoll_detail';

	public $idtm_protokoll_detail;
	public $idtm_activity;
	public $idtm_protokoll_detail_group;
	public $prtdet_topic;
	public $prtdet_descr;
	public $prtdet_cdate;
	public $idtm_user;
	public $idta_protokoll_ergebnistype;
	public $prtdet_wvl;
	public $prtdet_wvl_type;
        public $idtm_protokoll;
	
	public static $RELATIONS=array
    (
        'protokolldetailtype' => array(self::BELONGS_TO, 'ProtokollErgebnistypeRecord'),
    	'protokolldetailgroup' => array(self::BELONGS_TO, 'ProtokollDetailGroupRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>