<?php
/**
 * Auto generated by prado-cli.php on 2008-09-15 10:05:58.
 */
class ProzessTypeRecord extends TActiveRecord
{
	const TABLE='ta_prozess_type';

	public $idta_prozess_type;
	public $pro_type_name;

	public static $RELATIONS=array
    (
        'typepro' => array(self::HAS_MANY, 'ProzessRecord'),
    );
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>