<?php
/**
 * Auto generated by prado-cli.php on 2008-09-15 10:05:37.
 */
class ProzessRecord extends TActiveRecord
{
	const TABLE='tm_prozess';

	public $idtm_prozess;
	public $pro_name;
	public $pro_descr;
	public $parent_idtm_prozess;
	public $idta_prozess_type;
	public $pro_step;

	public static $RELATIONS=array
    (
        'protype' => array(self::BELONGS_TO, 'ProzessTypeRecord'),
    );
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>