<?php
/**
 * Auto generated by prado-cli.php on 2008-09-28 09:14:58.
 */
class RCTTValueRecord extends TActiveRecord
{
	const TABLE='tt_rcvalue';

	public $idtt_rcvalue;
	public $rcv_ewk;
	public $rcv_schaden;
	public $rcv_prio;
	public $rcv_cby;
	public $rcv_cdate;
	public $idtm_rcvalue;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static $RELATIONS=array
    (
        'rcttvaluercvalue' => array(self::BELONGS_TO, 'RCValueRecord'),
    );
}
?>