<?php
/**
 * Auto generated by prado-cli.php on 2010-10-14 08:23:25.
 */
class RechnungRecord extends TActiveRecord
{
	const TABLE='tm_rechnung';

	public $idtm_rechnung;
	public $idtm_organisation_from;
	public $idtm_organisation_to;
	public $rech_cdate;
	public $rech_date;
	public $rech_number;
	public $rech_intro;
        public $rech_extro;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>