<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:13:18.
 */
class ResCalendarRecord extends TActiveRecord
{
	const TABLE='ta_rescalendar';

	public $idta_rescalendar;
	public $rescal_name;
	public $rescal_descr;
	public $rescal_t1;
	public $rescal_h1;
	public $rescal_t2;
	public $rescal_h2;
	public $rescal_t3;
	public $rescal_h3;
	public $rescal_t4;
	public $rescal_h4;
	public $rescal_t5;
	public $rescal_h5;
	public $rescal_t6;
	public $rescal_h6;
	public $rescal_t7;
	public $rescal_h7;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>