<?php
/**
 * Auto generated by prado-cli.php on 2008-09-15 10:06:12.
 */
class RisikoTypeRecord extends TActiveRecord
{
	const TABLE='ta_risiko_type';

	public $idta_risiko_type;
	public $ris_type_name;

	public static $RELATIONS=array
    (
        'typeris' => array(self::HAS_MANY, 'RisikoRecord'),
    );
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>