<?php
/**
 * Auto generated by prado-cli.php on 2009-04-23 10:24:39.
 */
class SBZCollectorRecord extends TActiveRecord
{
	const TABLE='ta_sbz_collector';

	public $idta_sbz_collector;
	public $idta_struktur_bericht_zeilen;
	public $row_idta_struktur_bericht_zeilen;
	public $sbz_collector_operator;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>