<?php
/**
 * Auto generated by prado-cli.php on 2010-03-07 01:57:17.
 */
class SplasherRecord extends TActiveRecord
{
	const TABLE='ta_splasher';

	public $idta_splasher;
	public $from_idta_stammdaten_group;
	public $from_idta_feldfunktion;
	public $to_idta_stammdaten_group;
	public $to_idta_feldfunktion;
	public $spl_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>