<?php
/**
 * Auto generated by prado-cli.php on 2010-05-13 10:51:44.
 */
class StammdatenLinkRecord extends TActiveRecord
{
	const TABLE='ta_stammdaten_link';

	public $idta_stammdaten_link;
	public $idtm_stammdaten_from;
	public $idtm_stammdaten_to;
	public $idta_stammdaten_group;
	public $idta_feldfunktion_from;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>