<?php
/**
 * Auto generated by prado-cli.php on 2009-04-23 10:25:21.
 */
class StrukturBerichtSpaltenRecord extends TActiveRecord
{
	const TABLE='ta_struktur_bericht_spalten';

	public $idta_struktur_bericht_spalten;
	public $idta_perioden_gap;
	public $sbs_perioden_fix;
	public $sbs_cumulated;
	public $idta_variante;
	public $idta_struktur_bericht;
	public $sbs_order;
	public $sbs_input;
        public $sbs_idta_variante_fix;
        public $sbs_idtm_struktur;
        public $sbs_struktur_switch_type;
        public $sbs_bericht_operator;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>