<?php
/**
 * Auto generated by prado-cli.php on 2008-09-15 10:06:32.
 */
class StrukturTypeRecord extends TActiveRecord
{
	const TABLE='ta_struktur_type';

	public $idta_struktur_type;
	public $struktur_type_name;

	public static $RELATIONS=array
    (
        'typestr' => array(self::HAS_MANY, 'StrukturRecord'),
    );
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>