<?php
/**
 * Auto generated by prado-cli.php on 2008-12-26 02:02:55.
 */
class TerminOrganisationRecord extends TActiveRecord
{
	const TABLE='tm_termin_organisation';

	public $idtm_termin;
	public $idtm_organisation;
	public $idtm_termin_organisation;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>