<?php
/**
 * Auto generated by prado-cli.php on 2009-02-21 05:15:12.
 */
class TerminTypeRecord extends TActiveRecord
{
	const TABLE='ta_termin_type';

	public $idta_termin_type;
	public $ter_type_name;
	public $ter_type_descr;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>