<?php
/**
 * Auto generated by prado-cli.php on 2008-12-26 02:02:55.
 */
class TerminRessourceRecord extends TActiveRecord
{
	const TABLE='tm_termin_ressource';

	public $idtm_termin;
	public $idtm_ressource;
	public $idtm_termin_ressource;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>