<?php
/**
 * Auto generated by prado-cli.php on 2009-07-30 09:20:57.
 */
class TTSaisonRecord extends TActiveRecord
{
	const TABLE='tt_saisonalisierung';

	public $idtt_saisonalisierung;
	public $idta_saisonalisierung;
	public $idta_periode;
	public $sai_wert;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>