<?php
/**
 * Auto generated by prado-cli.php on 2010-03-07 01:57:40.
 */
class TTStammdatenRecord extends TActiveRecord
{
	const TABLE='tt_stammdaten';

	public $idtt_stammdaten;
	public $idta_variante;
	public $idta_feldfunktion;
	public $idta_periode;
	public $idtm_stammdaten;
	public $tt_stammdaten_value;
        
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>