<?php
/**
 * Auto generated by prado-cli.php on 2009-10-13 09:30:41.
 */
class TTStammdatenStammdatenRecord extends TActiveRecord
{
	const TABLE='tt_stammdaten_stammdaten';

	public $idtt_stammdaten_stammdaten;
	public $idtm_stammdaten_group; //the parent idtm_stammdaten
	public $idtm_stammdaten; //the actual idtm_stammdaten
        public $idta_stammdatensicht; //fuer welche sicht gelten die mappings

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>