<?php
/**
 * Auto generated by prado-cli.php on 2009-09-08 04:58:44.
 */
class UserFelderRecord extends TActiveRecord
{
	const TABLE='tt_user_felder';

	public $idtt_user_felder;
	public $user_id;
	public $tuf_feldname;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>