<?php
/**
 * Auto generated by prado-cli.php on 2008-04-25 09:06:38.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='tm_user';

	public $idtm_user;
	public $user_name;
	public $user_vorname;
	public $user_password;
	public $idtm_user_role;
	public $user_username;
	public $user_mail;

	
	public static $RELATIONS=array
    (
        'user_role' => array(self::HAS_MANY, 'UserRoleRecord','idtm_user_role'),
    );
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
		
}
?>