<?php
/**
 * Auto generated by prado-cli.php on 2009-03-03 02:39:52.
 */
class VarianteRecord extends TActiveRecord
{
	const TABLE='ta_variante';

	public $idta_variante;
	public $idtm_user;
	public $var_descr;
	public $w_id_variante;
        public $var_default;
        public $idta_perioden;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>