<?php
/**
 * Auto generated by prado-cli.php on 2009-01-05 10:50:12.
 */
class VerteilerRecord extends TActiveRecord
{
	const TABLE='tm_verteiler';

	public $idtm_verteiler;
	public $ver_name;
	public $ver_descr;
	public $ver_valid;
	public $ver_zyklus;
	public $ver_day;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>