<?php
/**
 * Auto generated by prado-cli.php on 2008-05-25 12:17:04.
 */
class WarenRecord extends TActiveRecord
{
	const TABLE='ta_waren';

	public $idta_waren;
	public $waren_artikelnummer;
	public $waren_ean;
	public $waren_bezeichnung;
	public $waren_beschreibung;
	public $idtm_waren_kategorie;
	public $waren_menge;
	public $waren_gewicht;
	public $waren_preis;
	public $idtm_preis_kategorie;
	public $waren_dat_ea;
	public $waren_dat_lb;
	public $idta_adresse;
	public $waren_typ;
	
	public static $RELATIONS=array
    (
        'warenadresse' => array(self::BELONGS_TO, 'AdresseRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>