<?php
/**
 * Auto generated by prado-cli.php on 2008-05-25 12:17:55.
 */
class WarenParteiRecord extends TActiveRecord
{
	const TABLE='ta_waren_has_ta_partei';

	public $idta_waren_has_ta_partei;
	public $idta_partei_vk;
	public $idta_partei_ek;
	public $dat_ea;
	public $stat_status;
	public $idta_waren;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>