<?php
/**
 * Auto generated by prado-cli.php on 2008-05-05 11:37:08.
 */
class WarenKategorieRecord extends TActiveRecord
{
	const TABLE='tm_waren_kategorie';

	public $idtm_waren_kategorie;
	public $waren_kategorie_name;
	public $waren_kategorie_beschreibung;
	public $parent_idtm_waren_kategorie;

	public $tree_parent;

	public static $RELATIONS=array
    (
 		'tree_parent' => array(self::BELONGS_TO, 'WarenKategorieRecord', 'parent_idtm_waren_kategorie'),
    );
	
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>