<?php
/**
 * Auto generated by prado-cli.php on 2009-03-15 08:20:30.
 */
class ZeiterfassungRecord extends TActiveRecord
{
	const TABLE='tm_zeiterfassung';

	public $idtm_zeiterfassung;
	public $idtm_organisation;
	public $idtm_activity;
	public $zeit_date;
	public $zeit_starttime;
	public $zeit_endtime;
	public $zeit_break;
	public $zeit_dauer;
	public $idta_kosten_status;
        public $zeit_descr;
        public $zeit_abgerechnet;
        public $zeit_checked;
        public $idtm_prozess; //(int) verbindung zum Prozess
        public $zeit_typ; //(int) verbindung zum Prozess

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>