<?php
/**
 * Auto generated by prado-cli.php on 2008-11-30 07:21:34.
 */
class ZieleTypeRecord extends TActiveRecord
{
	const TABLE='ta_ziele_type';

	public $idta_ziele_type;
	public $zie_type_name;
	
	public static $RELATIONS=array
    (
        'typeziele' => array(self::HAS_MANY, 'ZieleRecord'),
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>