<?php
/**
 * Auto generated by prado-cli.php on 2008-12-23 08:05:07.
 */
class ActivityActivityView extends TActiveRecord
{
	const TABLE='vv_activity_activity';

	public $idta_activity_activity;
	public $idtm_activity;
	public $pre_idtm_activity;
	public $actact_type;
	public $act_name;
	public $pre_act_name;
        public $actact_minz;
	public $actact_maxz;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>