<?php
/**
 * Auto generated by prado-cli.php on 2008-12-24 12:06:02.
 */
class ActivityZieleView extends TActiveRecord
{
	const TABLE='vv_activity_ziele';

	public $idtt_ziele;
	public $idtm_activity;
	public $idtm_activity_has_tt_ziele;
	public $ttzie_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>