<?php
/**
 * Auto generated by prado-cli.php on 2010-03-17 11:27:18.
 */
class AufgabenView extends TActiveRecord
{
	const TABLE='vv_aufgaben';

	public $org_responsible;
	public $org_speachpartner;
	public $idtm_aufgaben;
	public $auf_tabelle;
	public $auf_id;
	public $idtm_organisation;
	public $auf_cdate;
	public $auf_beschreibung;
	public $auf_tdate;
	public $auf_priority;
	public $auf_name;
	public $auf_done;
	public $auf_dauer;
	public $auf_ddate;
	public $auf_idtm_organisation;
	public $idta_aufgaben_type;
	public $auf_tag;
	public $auf_zeichen_eigen;
	public $auf_zeichen_fremd;
	public $auf_type_name;
        public $auf_cby;
        public $auf_deleted;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>