<?php
/**
 * Auto generated by prado-cli.php on 2009-01-06 04:06:36.
 */
class ProtokollDetailAufgabeView extends TActiveRecord
{
	const TABLE='vv_protokoll_detail_aufgabe';

	public $idtm_protokoll_detail;
        public $idtm_protokoll_detail_group;
	public $idtm_activity;
	public $prtdet_topic;
	public $prtdet_descr;
	public $prtdet_cdate;
        public $idtm_protokoll;
	public $idtm_user;
	public $idta_protokoll_ergebnistype;
	public $prtdet_wvl;
	public $prtdet_wvl_type;
	public $idtm_aufgaben;
	public $auf_tabelle;
	public $auf_id;
	public $idtm_organisation;
	public $auf_cdate;
	public $auf_beschreibung;
	public $auf_tdate;
	public $auf_priority;
	public $auf_name;
	public $auf_done;
	public $auf_dauer;
	public $auf_ddate;
        public $auf_cby;
        public $auf_deleted;
        public $auf_idtm_organisation;
        public $idta_aufgaben_type;
        public $auf_tag;
        public $auf_zeichen_eigen;
        public $auf_zeichen_fremd;
        public $act_name;
        public $act_lft;
        public $act_rgt;
        public $act_pspcode;
        public $org_name;
        public $idta_organisation_art;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>