<?php
/**
 * Auto generated by prado-cli.php on 2008-12-26 08:42:41.
 */
class TerminRessourceView extends TActiveRecord
{
	const TABLE='vv_termin_ressource';

	public $idtm_termin;
	public $idtm_ressource;
	public $idtm_termin_ressource;
	public $res_name;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>